development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails-bootstrap-boilerplate
  pool: 5
  username: rails
  password: 

test:
  adapter: sqlite3
#  database: db/test.sqlite3
  database: ':memory:'
